kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: sdesbure/yamllint
    commands:
      - yamllint -d relaxed .drone.yml
  - name: test
    depends_on:
      - lint
    image: golang:1.14
    environment:
      YOUTUBE_API_KEY:
        from_secret: YOUTUBE_API_KEY
    commands:
      - cd pkg/apikey && go test
      - cd ../channelid && go test
      - cd parser && go test
  - name: build
    depends_on:
      - lint
    image: golang:1.14
    environment:
      CGO_ENABLED: "0"
    commands:
      - echo success
  - name: run
    depends_on:
      - build
    image: alpine:3.11.6
    environment:
      YOUTUBE_API_KEY:
        from_secret: YOUTUBE_API_KEY
    commands:
      - echo success
